module.exports = {
  User: require("./User"),
  StudentProfile: require("./StudentProfile"),
  TeacherProfile: require("./TeacherProfile"),
  AdminProfile: require("./AdminProfile"),
  TwinProfile: require("./TwinProfile"),
  School: require("./School"),
  Subject: require("./Subject"),
  TeacherSubject: require("./TeacherSubject"),
  Class: require("./Class"),
  StudentEnrollment: require("./StudentEnrollment"),
  Textbook: require("./Textbook"),
  VirtualLabResource: require("./VirtualLabResource"),
  InteractiveMetadata: require("./InteractiveMetadata"),
  IngestionJob: require("./IngestionJob"),
  Quiz: require("./Quiz"),
  QuizAssignment: require("./QuizAssignment"),
  Question: require("./Question"),
  QuizAttempt: require("./QuizAttempt"),
  StudentAnswer: require("./StudentAnswer"),
  ChatSession: require("./ChatSession"),
  ChatMessage: require("./ChatMessage"),
  Achievement: require("./Achievement"),
  StudentAchievement: require("./StudentAchievement"),
  Subscription: require("./Subscription"),
  PaymentTransaction: require("./PaymentTransaction"),
};
